---
title: "Vectors, Lists & Data Frames"
author: "Halina Do-Linh"
date: "8/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Create a vector called vec_1
```{r}
vec_1 <- c(2, 5, 9, 10, 8, 12, 1, 0)
class(vec_1)
typeof(vec_1)

vec_1_e3 <- vec_1[3]
vec_1_e3

vec_1_e1 <- vec_1[1]
vec_1_e1

vec_1_e5to7 <- vec_1[5:7]
vec_1_e5to7

vec_1_char <- as.character(vec_1)
vec_1_char
```

## Create another vector called vec_2
```{r}
vec_2 <- c(town = "Santa Barbara", location = "Rincon", swell = "south")
class(vec_2)
vec_2[2]
vec_2["location"]

# note that the length of vec_2 is 3

vec_2_e2 <- vec_2[2]
vec_2_e2
```

## Create a data frame
```{r}
df_1 <- data.frame(region = c("A", "B", "A", "D"),
                   species = c("otter", "great white", "sea lion", "gray whale"),
                   count = c(12, 2, 36, 6))

df_1

class(df_1)

class(df_1$species)

# I could also find max_count using max_count <- df_1[3,3] but this would be bad storage because if the data frame is updated this could change the location of the max count in the Count column

max_count <- max(df_1$count)
max_count
```


